### PR TITLE
Update plot caption

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

**Review by msevestre — COMMENTED** [review]
@Yuri05 @pchelle 
I am stunned here. Why is the size of the graph changing? In one PR, they become bigger, and now smaller again lol. I did not change anything in the QP or the script. Just keep running it again and again

**Comment by Yuri05** [comment]
@msevestre is it something like few bytes difference or more significant?

**Comment by msevestre** [comment]
the size changes
image

and in the PR before, it went from small to big.

**Comment by msevestre** [comment]
6250 vs 5000 
Quite significant lol

**Comment by Yuri05** [comment]
hmm. I have no idea and would not expect this. @pchelle any thoughts?

**Pull request merged**
